#!/bin/bash

CLIENT_VERSION_STRING=$(docker version | grep 'Client version')
CLIENT_VERSION=${CLIENT_VERSION_STRING#Client version: }

if [ "${DOCKER_CERTS_PATH}" != "" ] ; then
  CERTS_PATH="-v ${DOCKER_CERT_PATH}:${DOCKER_CERT_PATH}"
else
  CERTS_PATH=""
fi

docker run -e DOCKER_CERT_PATH="{$DOCKER_CERT_PATH}" -e DOCKER_TLS_VERIFY="${DOCKER_TLS_VERIFY}" -e DOCKER_HOST="${DOCKER_HOST}" ${CERTS_PATH} -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm dsanders11/docker-cleanup-volumes:${CLIENT_VERSION} $@
