#!/bin/bash

CLIENT_VERSION_STRING=$(docker version | grep 'Client version')
CLIENT_VERSION=${CLIENT_VERSION_STRING#Client version: }

docker run -e DOCKER_CERT_PATH=$DOCKER_CERT_PATH -e DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY -e DOCKER_HOST=$DOCKER_HOST -v $DOCKER_CERT_PATH:$DOCKER_CERT_PATH -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm dsanders11/docker-cleanup-volumes:${CLIENT_VERSION} $@
